name: Build and Push to ACR

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'AzureFunctionLoad/**'
permissions:
  id-token: write
  contents: read
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: az acr login --name ${{ secrets.REGISTRY_NAME }}

    - name: Build and tag Docker image
      run: |
        IMAGE=${{ secrets.REGISTRY_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest
        docker build -t $IMAGE .
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Push image to ACR
      run: docker push $IMAGE

    - name: Deploy to Azure Container App
      run: |
        az containerapp update \
          --name mysuperapp \
          --resource-group myvm1_group_05102216 \
          --image ${{ env.IMAGE }}
